on: [push, pull_request]

name: Build/test taglogic

jobs:
  test:
    name: taxlogic tests (no WASM)
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        rust:
          - stable
          - beta
          - nightly
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true

      - run: cd taglogic

      - name: Run cargo test
        uses: actions-rs/cargo@v1
        working-directory: taglogic
        with:
          command: test
